### ISSUE TITLE
Lowest Common Ancestor of a Binary Search Tree

### ISSUE THREAD

**Issue by Sonia312** [Google-Developer-Student-Club-CCOEW/Competitive-Programming-2023-GDSC-CUMMINS-X-GDSC-MMCOE#102]
**Write code in the preferred language and attach output with it.**

Given a binary search tree (BST), find the lowest common ancestor (LCA) node of two given nodes in the BST.

According to the [definition of LCA on Wikipedia](https://en.wikipedia.org/wiki/Lowest_common_ancestor): “The lowest common ancestor is defined between two nodes p and q as the lowest node in T that has both p and q as descendants (where we allow a node to be a descendant of itself).”

 

**Example 1:**

<img width="149" alt="image" src="https://github.com/Google-Developer-Student-Club-CCOEW/Competitive-Programming-2023/assets/101570119/1600a33b-f5d2-4cca-be9e-0a62672a980b">

Input: root = [6,2,8,0,4,7,9,null,null,3,5], p = 2, q = 8
Output: 6
Explanation: The LCA of nodes 2 and 8 is 6.

**Example 2:**

<img width="149" alt="image" src="https://github.com/Google-Developer-Student-Club-CCOEW/Competitive-Programming-2023/assets/101570119/34417b87-50ce-412f-a6a6-a826e4046259">

Input: root = [6,2,8,0,4,7,9,null,null,3,5], p = 2, q = 4
Output: 2
Explanation: The LCA of nodes 2 and 4 is 2, since a node can be a descendant of itself according to the LCA definition.

**Example 3:**

Input: root = [2,1], p = 2, q = 1
Output: 2

**Comment by MOHIT-PANDEY215** [comment]
Hey @Sonia312 , Please assign this issue to me.

**Comment by Swetathakare** [comment]
Could you assign this issue to me ?
Name :Sweta Thakare
Roll no :UCE2022654
e.mail :[sweta.thakare@cumminscollege.in]

**Comment by Lavanyawaghulde** [comment]
Could you assign this issue to me ?
Name : Lavanya Waghulde
Roll no :UCE2022362
e.mail : lavanya.waghulde@cumminscollege.in

**Comment by Lavanyawaghulde** [comment]
@Sonia312 I have submitted solution . Could you please check?
