### ISSUE TITLE
Median of Two Sorted Arrays

### ISSUE THREAD

**Issue by Sonia312** [Google-Developer-Student-Club-CCOEW/Competitive-Programming-2023-GDSC-CUMMINS-X-GDSC-MMCOE#105]
**Write code in the preferred language and attach output with it.**

Given two sorted arrays nums1 and nums2 of size m and n respectively, return the median of the two sorted arrays.

The overall run time complexity should be O(log (m+n)).

 

**Example 1:**

Input: nums1 = [1,3], nums2 = [2]
Output: 2.00000
Explanation: merged array = [1,2,3] and median is 2.

**Example 2:**

Input: nums1 = [1,2], nums2 = [3,4]
Output: 2.50000
Explanation: merged array = [1,2,3,4] and median is (2 + 3) / 2 = 2.5.

**Comment by Esha-01** [comment]
hey @Sonia312 i know how to do this , could you please assign this to me

**Comment by vivekPatil45** [comment]
@Sonia312 Can you please assign this issue to me under HACKTOBERFEST

**Comment by RiRa25** [comment]
Can you please assign this issue to me?
Name- Richa Rathi
email - richa.rathi@cumminscollege.in
Cnumber - UEC2022324
Branch - ENTC
Year - SY

**Comment by Swetathakare** [comment]
Could you assign this issue to me ?
Name :Sweta Thakare
Roll no :UCE2022654
e.mail :[sweta.thakare@cumminscollege.in]

**Comment by srushtikage** [comment]
Hello, please assign this issue to me i want to work on it.
Srushti Kage
UCE2022531
Cummins College of Engineering
Second year

**Comment by srushtikage** [comment]
While creating the pull request my main branch got compared and the square of sorted array code also got added which was there  in my main branch of forked repo along with the median of sorted arrays also got added. Please take into consideration the Median of 2 sorted arrays Code File only while checking. 
Thank you.
