### ISSUE TITLE
Count Negative Numbers in a Sorted Matrix

### ISSUE THREAD

**Issue by Sonia312** [Google-Developer-Student-Club-CCOEW/Competitive-Programming-2023-GDSC-CUMMINS-X-GDSC-MMCOE#106]
**Write code in the preferred language and attach output with it.**

Given a m x n matrix grid which is sorted in non-increasing order both row-wise and column-wise, return the number of negative numbers in grid.

 

**Example 1:**

Input: grid = [[4,3,2,-1],[3,2,1,-1],[1,1,-1,-2],[-1,-1,-2,-3]]
Output: 8
Explanation: There are 8 negatives number in the matrix.

**Example 2:**

Input: grid = [[3,2],[1,0]]
Output: 0

**Comment by Satvik-Garg** [comment]
@Sonia312 
kindly assign this issue to me

**Comment by Nikunjpatel2411** [comment]
Hello
could you please assign me this issue under #hacktoberfest2023
I will try my best...

**Comment by hitali-khachane** [comment]
Can u please Assign me this issue
C number-UCE2021434
Name-Hitali Khachane
[hitali.khachane@cumminscollege.in](mailto:hitali.khachane@cumminscollege.in)
Cummins college of engineering pune

**Comment by RiRa25** [comment]
Can you assign this issue to me?
Name- Richa Rathi
email - richa.rathi@cumminscollege.in

**Comment by Sonia312** [comment]
Count Negative Numbers in a Sorted Matrix solved by hitali-khachane
