### ISSUE TITLE
Middle of the Linked List

### ISSUE THREAD

**Issue by Sonia312** [Google-Developer-Student-Club-CCOEW/Competitive-Programming-2023-GDSC-CUMMINS-X-GDSC-MMCOE#11]
**Write code in the preferred language and attach output with it.**

Given the head of a singly linked list, return the middle node of the linked list.

If there are two middle nodes, return the second middle node.

**Example 1:**

<img width="407" alt="image" src="https://github.com/Google-Developer-Student-Club-CCOEW/Competitive-Programming-2023/assets/101570119/b7090990-4343-4717-b454-2bef136a8bd1">

Input: head = [1,2,3,4,5]
Output: [3,4,5]
Explanation: The middle node of the list is node 3.

**Example 2:**

<img width="428" alt="image" src="https://github.com/Google-Developer-Student-Club-CCOEW/Competitive-Programming-2023/assets/101570119/bf0831b2-9edb-4566-9737-c6ae0aabf810">

Input: head = [1,2,3,4,5,6]
Output: [4,5,6]
Explanation: Since the list has two middle nodes with values 3 and 4, we return the second one.

**Comment by iliketrains42** [comment]
Could you please assign this to me?

**Comment by avyuktsoni0731** [comment]
Hi @Sonia312 . Can I please get this issue assigned to me, i have worked on it, and made a pull request. The program works good!

Thank you! :)

**Comment by hitali-khachane** [comment]
Can u please Assign me this issue
C number-UCE2021434
Name-Hitali Khachane
[hitali.khachane@cumminscollege.in](mailto:hitali.khachane@cumminscollege.in)
Cummins college of engineering pune
