### ISSUE TITLE
Search in Rotated Sorted Array

### ISSUE THREAD

**Issue by Sonia312** [Google-Developer-Student-Club-CCOEW/Competitive-Programming-2023-GDSC-CUMMINS-X-GDSC-MMCOE#110]
**Write code in the preferred language and attach output with it.**

There is an integer array nums sorted in ascending order (with distinct values).

Prior to being passed to your function, nums is possibly rotated at an unknown pivot index k (1 <= k < nums.length) such that the resulting array is [nums[k], nums[k+1], ..., nums[n-1], nums[0], nums[1], ..., nums[k-1]] (0-indexed). For example, [0,1,2,4,5,6,7] might be rotated at pivot index 3 and become [4,5,6,7,0,1,2].

Given the array nums after the possible rotation and an integer target, return the index of target if it is in nums, or -1 if it is not in nums.

You must write an algorithm with O(log n) runtime complexity.

 

**Example 1:**

Input: nums = [4,5,6,7,0,1,2], target = 0
Output: 4

**Example 2:**

Input: nums = [4,5,6,7,0,1,2], target = 3
Output: -1

**Example 3:**

Input: nums = [1], target = 0
Output: -1

**Comment by Snowfall22** [comment]
Hi, would like to take this up

**Comment by hitali-khachane** [comment]
Can u please Assign me this issue
C number-UCE2021434
Name-Hitali Khachane
hitali.khachane@cumminscollege.in
Cummins college of engineering pune

**Comment by Tanishaclippy** [comment]
Assign me this issue
Name;Tanisha jawale
Year:2nd
email id;tanishajawale@cumminscollege.in

**Comment by Swetathakare** [comment]
Could you assign this issue to me ?
Name       :Sweta Thakare
Roll no     :UCE2022654
e.mail       :sweta.thakare@cumminscollege.in
