### ISSUE TITLE
Count of Smaller Numbers After Self

### ISSUE THREAD

**Issue by Sonia312** [Google-Developer-Student-Club-CCOEW/Competitive-Programming-2023-GDSC-CUMMINS-X-GDSC-MMCOE#112]
**Write code in the preferred language and attach output with it.**

Given an integer array nums, return an integer array counts where counts[i] is the number of smaller elements to the right of nums[i].

 

**Example 1:**

Input: nums = [5,2,6,1]
Output: [2,1,1,0]
Explanation:
To the right of 5 there are 2 smaller elements (2 and 1).
To the right of 2 there is only 1 smaller element (1).
To the right of 6 there is 1 smaller element (1).
To the right of 1 there is 0 smaller element.

**Example 2:**

Input: nums = [-1]
Output: [0]

**Example 3:**

Input: nums = [-1,-1]
Output: [0,0]

**Comment by Veerhan-glitch** [comment]
I can take this up if u want

**Comment by sejalphatangare** [comment]
Hi! pls assign this issue to me
Sejal Phatangare
UCE2021457
Cummins College of Engineering,Pune

**Comment by sharwaritijare** [comment]
@Sonia312 Can u please assign me this issue
UEC2023260
Sharwari
sharwari.tijare@cumminscollege.in)
Cummins college of engineering Pune
