### ISSUE TITLE
Shortest Subarray with Sum at Least K

### ISSUE THREAD

**Issue by Sonia312** [Google-Developer-Student-Club-CCOEW/Competitive-Programming-2023-GDSC-CUMMINS-X-GDSC-MMCOE#113]
**Write code in the preferred language and attach output with it.**

Given an integer array nums and an integer k, return the length of the shortest non-empty subarray of nums with a sum of at least k. If there is no such subarray, return -1.

A subarray is a contiguous part of an array.

 

**Example 1:**

Input: nums = [1], k = 1
Output: 1

**Example 2:**

Input: nums = [1,2], k = 4
Output: -1

**Example 3:**

Input: nums = [2,-1,2], k = 3
Output: 3

**Comment by Snowfall22** [comment]
May I take this up please

**Comment by kittoteja** [comment]
Please assign the issue to me

**Comment by aniketsinha620** [comment]
Hi @Sonia312 , please assign this to me

**Comment by abhinavs05** [comment]
hey @Sonia312 ,please assign this issue to me

**Comment by vaishnavim141003** [comment]
Solved the issue #Shortest Subarray with Sum at Least K #113 by using python.

**Comment by aditi3004** [comment]
I'm enthusiastic about contributing to this issue. May I kindly request the assignment of this issue?
-Aditi Sharma
TY CSE,CCOEW

**Comment by vrishitagharte** [comment]
Vrishita Gharte
UEC2021128
vrishitagharte1@gmail.com
ENTC
TY 
can i please work on this issue?
