### ISSUE TITLE
Subarray Sums Divisible by K

### ISSUE THREAD

**Issue by saakshii12** [Google-Developer-Student-Club-CCOEW/Competitive-Programming-2023-GDSC-CUMMINS-X-GDSC-MMCOE#12]
**Write code in the preferred language and attach output with it.**

**Given an integer array nums and an integer k, return the number of non-empty subarrays that have a sum divisible by k.**

A subarray is a contiguous part of an array.

**Example 1:**

Input: nums = [4,5,0,-2,-3,1], k = 5
Output: 7
Explanation: There are 7 subarrays with a sum divisible by k = 5:
[4, 5, 0, -2, -3, 1], [5], [5, 0], [5, 0, -2, -3], [0], [0, -2, -3], [-2, -3]

**Example 2:**

Input: nums = [5], k = 9
Output: 0

**Comment by Piyusha2512** [comment]
Can you assign this issue to me?
Name : Piyusha Patil
UCE2022004
TY COMP
