### ISSUE TITLE
Convert Binary Number in a Linked List to Integer

### ISSUE THREAD

**Issue by Sonia312** [Google-Developer-Student-Club-CCOEW/Competitive-Programming-2023-GDSC-CUMMINS-X-GDSC-MMCOE#13]
**Write code in the preferred language and attach output with it.**

Given head which is a reference node to a singly-linked list. The value of each node in the linked list is either 0 or 1. The linked list holds the binary representation of a number.

Return the decimal value of the number in the linked list.

The most significant bit is at the head of the linked list.

 

**Example 1:**

<img width="294" alt="image" src="https://github.com/Google-Developer-Student-Club-CCOEW/Competitive-Programming-2023/assets/101570119/4d9f8d95-7cbe-4b35-9093-936015df0e08">

Input: head = [1,0,1]
Output: 5
Explanation: (101) in base 2 = (5) in base 10

**Example 2:**

Input: head = [0]
Output: 0

**Comment by Priyanshu229** [comment]
Hey @Sonia312 @saakshii12 
Please assign this issue to me.

**Comment by saniyadighe** [comment]
Please assign this issue to me
Saniya Dighe
UCE2021416
saniya.dighe@cumminscollege.in
