### ISSUE TITLE
Permutations

### ISSUE THREAD

**Issue by suryaprakashpandey** [Google-Developer-Student-Club-CCOEW/Competitive-Programming-2023-GDSC-CUMMINS-X-GDSC-MMCOE#137]
**Write code in the preferred language and attach output with it.**

A permutation of integers 1,2,…,n is called beautiful if there are no adjacent elements whose difference is 1.

Given n, construct a beautiful permutation if such a permutation exists.

**Input**
The only input line contains an integer n.

**Output**
Print a beautiful permutation of integers 1,2,…,n. If there are several solutions, you may print any of them. If there are no solutions, print "NO SOLUTION".

 
**Example 1:**

Input: 5
Output: 4 2 5 3 1

**Example 2:**
Input: 3
Output: NO SOLUTION

**Comment by akhilender-bongirwar** [comment]
I want to work on this. Please assign me : ).

**Comment by anu-shka-k** [comment]
Hi @suryaprakashpandey , could you please assign this issue to me?

**Comment by VaishnaviSaraf** [comment]
hello ,
I am Vaishnavi Saraf
from CCOEW
Can you assign me this problem?

**Comment by aditi3004** [comment]
I'm enthusiastic about contributing to this issue. May I kindly request the assignment of this issue?
-Aditi Sharma
TY CSE,CCOEW
