### ISSUE TITLE
Two Sets

### ISSUE THREAD

**Issue by suryaprakashpandey** [Google-Developer-Student-Club-CCOEW/Competitive-Programming-2023-GDSC-CUMMINS-X-GDSC-MMCOE#138]
**Write code in the preferred language and attach output with it.**

Your task is to divide the numbers 1,2,…,n into two sets of equal sum.

**Input**
The only input line contains an integer n.

**Output**
Print "YES", if the division is possible, and "NO" otherwise.

After this, if the division is possible, print an example of how to create the sets. First, print the number of elements in the first set followed by the elements themselves in a separate line, and then, print the second set in a similar way.
 
**Example 1**

Input: 7
Output: 
YES
4
1 2 4 7
3
3 5 6

**Example 2**

Input: 6
Output:
NO

**Comment by maskboyAvi** [comment]
@suryaprakashpandey I would like to work on this issue. Please assign it to me.

**Comment by DhritiSoni4** [comment]
I would like to contribute. Please assign.

**Comment by vaishnavim141003** [comment]
two sets #138 solved .. [Create two sets](https://github.com/vaishnavim141003/Competitive-Programming-2023-GDSC-CUMMINS-X-GDSC-MMCOE/commit/a01717a877a51a26fd4544eb69bd4e73bf27a55b) https://github.com/Google-Developer-Student-Club-CCOEW/Competitive-Programming-2023-GDSC-CUMMINS-X-GDSC-MMCOE/issues/138

**Comment by vaishnavim141003** [comment]
Vaishnavi Mahajan-Cummins college of engineering.
I would like to work on this issue.
So please assign this issue(#138) to me.

**Comment by Eesha04** [comment]
Eesha Satvalekar - Cummins College
I would like to work on this issue.
Please assign this (#138) issue to me.
