### ISSUE TITLE
Minimum Size Subarray Sum

### ISSUE THREAD

**Issue by saakshii12** [Google-Developer-Student-Club-CCOEW/Competitive-Programming-2023-GDSC-CUMMINS-X-GDSC-MMCOE#14]
**Write code in the preferred language and attach output with it.**

**Given an array of positive integers nums and a positive integer target, return the minimal length of a 
subarray whose sum is greater than or equal to target. If there is no such subarray, return 0 instead.**

**Example 1:**

Input: target = 7, nums = [2,3,1,2,4,3]
Output: 2
Explanation: The subarray [4,3] has the minimal length under the problem constraint.

**Example 2:**

Input: target = 4, nums = [1,4,4]
Output: 1

**Example 3:**

Input: target = 11, nums = [1,1,1,1,1,1,1,1]
Output: 0

**Comment by maskboyAvi** [comment]
@saakshii12 I would like to work on this issue. Please assign it to me.

**Comment by saniyadighe** [comment]
Please assign this issue to me.
Saniya Dighe
UCE2021416
TY COMP A
saniya.dighe@cumminscollege.in
