### ISSUE TITLE
Stick Lengths

### ISSUE THREAD

**Issue by suryaprakashpandey** [Google-Developer-Student-Club-CCOEW/Competitive-Programming-2023-GDSC-CUMMINS-X-GDSC-MMCOE#144]
**Write code in the preferred language and attach output with it.**

There are n sticks with some lengths. Your task is to modify the sticks so that each stick has the same length.

You can either lengthen and shorten each stick. Both operations cost x where x is the difference between the new and original length.

What is the minimum total cost?

**Input**
The first input line contains an integer n: the number of sticks.

Then there are n integers: p1,p2,...,pn: the lengths of the sticks.

**Output**
Print one integer: the minimum total cost.
 
**Example:**

Input:
5
2 3 1 5 2
Output: 5

**Comment by isha0904** [comment]
Can you assign me this Issue?
Name -> Isha Baviskar
Year -> 2nd 
C no.-> UCE2022427
E-mail -> baviskarisha2194@gmail.com

**Comment by NigeeHettige** [comment]
Hi,
can you assign me to this?

**Comment by isha0904** [comment]
I have created the Pull Request for this Issue. Please check.

**Comment by Pankaj4152** [comment]
Can you please assign this to me?
