### ISSUE TITLE
Traffic Lights

### ISSUE THREAD

**Issue by suryaprakashpandey** [Google-Developer-Student-Club-CCOEW/Competitive-Programming-2023-GDSC-CUMMINS-X-GDSC-MMCOE#145]
**Write code in the preferred language and attach output with it.**

There is a street of length x whose positions are numbered 0,1,…,x. Initially there are no traffic lights, but n sets of traffic lights are added to the street one after another.

Your task is to calculate the length of the longest passage without traffic lights after each addition.

**Input**
The first input line contains two integers x and n: the length of the street and the number of sets of traffic lights.

Then, the next line contains n integers p1,p2,…,pn: the position of each set of traffic lights. Each position is distinct.

**Output**
Print the length of the longest passage without traffic lights after each addition.

**Example:**

Input:
8 3
3 6 2
Output:
5 3 3

**Comment by 51tejalhajari** [comment]
can you please assign this issue to me

**Comment by aditi3004** [comment]
I'm enthusiastic about contributing to this issue. May I kindly request the assignment of this issue?
-Aditi Sharma
TY CSE,CCOEW

**Comment by Pankaj4152** [comment]
Can you please assign this to me?
