### ISSUE TITLE
Minimizing Coins

### ISSUE THREAD

**Issue by suryaprakashpandey** [Google-Developer-Student-Club-CCOEW/Competitive-Programming-2023-GDSC-CUMMINS-X-GDSC-MMCOE#148]
**Write code in the preferred language and attach output with it.**

Consider a money system consisting of n coins. Each coin has a positive integer value. Your task is to produce a sum of money x using the available coins in such a way that the number of coins is minimal.

For example, if the coins are {1,5,7} and the desired sum is 11, an optimal solution is 5+5+1 which requires 3 coins.

**Input**
The first input line has two integers n and x: the number of coins and the desired sum of money.

The second line has n distinct integers c1,c2,…,cn: the value of each coin.

**Output**
Print one integer: the minimum number of coins. If it is not possible to produce the desired sum, print -1.
 
**Example**

Input:
3 11
1 5 7
Output: 3

**Comment by akanksha1131** [comment]
Can you please assign this to me?
Akanksha Kale TY IT Cummins
