### ISSUE TITLE
Reverse Linked List

### ISSUE THREAD

**Issue by Sonia312** [Google-Developer-Student-Club-CCOEW/Competitive-Programming-2023-GDSC-CUMMINS-X-GDSC-MMCOE#15]
**Write code in the preferred language and attach output with it.**

Given the head of a singly linked list, reverse the list, and return the reversed list.

 

**Example 1:**

<img width="404" alt="image" src="https://github.com/Google-Developer-Student-Club-CCOEW/Competitive-Programming-2023/assets/101570119/0c62d8bd-7d2d-4165-b08e-ed1698ab8da6">

Input: head = [1,2,3,4,5]
Output: [5,4,3,2,1]

**Example 2:**

<img width="137" alt="image" src="https://github.com/Google-Developer-Student-Club-CCOEW/Competitive-Programming-2023/assets/101570119/d44eb985-5939-4fc6-8e10-cbd408ea37ea">

Input: head = [1,2]
Output: [2,1]

**Example 3:**

Input: head = []
Output: []

**Comment by vivekPatil45** [comment]
@Sonia312 Can you please assign this issue to me under HACKTOBERFEST

**Comment by Mani1881** [comment]
hey @saakshii12 can u please assign this issue to me.

**Comment by Piyusha2512** [comment]
Can you assign this issue to me?
Piyusha Patil UCE2022004
TY COMP

**Comment by janhavibagret** [comment]
Can you please assign me this issue? I would like to work on it.
