### ISSUE TITLE
Array Description

### ISSUE THREAD

**Issue by suryaprakashpandey** [Google-Developer-Student-Club-CCOEW/Competitive-Programming-2023-GDSC-CUMMINS-X-GDSC-MMCOE#150]
**Write code in the preferred language and attach output with it.**

You know that an array has n integers between 1 and m, and the absolute difference between two adjacent values is at most 1.

Given a description of the array where some values may be unknown, your task is to count the number of arrays that match the description.

**Input**
The first input line has two integers n and m: the array size and the upper bound for each value.

The next line has n integers x1,x2,…,xn: the contents of the array. Value 0 denotes an unknown value.

**Output**
Print one integer: the number of arrays modulo 10^9+7.

**Example:**

Input:
3 5
2 0 2
Output: 3

Explanation: The arrays [2,1,2], [2,2,2] and [2,3,2] match the description.

**Comment by 51tejalhajari** [comment]
Can u please assign this issue to me ?
Name -> Tejal Hajari
SY EnTC
E-mail -> tejal.hajari@cumminscollege.in

**Comment by 51tejalhajari** [comment]
Didi This issue is assigned to me but I got mail that it has merged so
what should I do now??
