### ISSUE TITLE
Removal Game

### ISSUE THREAD

**Issue by suryaprakashpandey** [Google-Developer-Student-Club-CCOEW/Competitive-Programming-2023-GDSC-CUMMINS-X-GDSC-MMCOE#151]
**Write code in the preferred language and attach output with it.**

There is a list of n numbers and two players who move alternately. On each move, a player removes either the first or last number from the list, and their score increases by that number. Both players try to maximize their scores.

What is the maximum possible score for the first player when both players play optimally?

**Input**
The first input line contains an integer n: the size of the list.

The next line has n integers x1,x2,…,xn: the contents of the list.

**Output**
Print the maximum possible score for the first player.
 
**Example:**

Input:
4
4 5 1 3
Output: 8

**Comment by RishabhDhawad** [comment]
Hey, Can I also work on this issue?

**Comment by Pankaj4152** [comment]
Can you please assign this to me?
