### ISSUE TITLE
Projects

### ISSUE THREAD

**Issue by suryaprakashpandey** [Google-Developer-Student-Club-CCOEW/Competitive-Programming-2023-GDSC-CUMMINS-X-GDSC-MMCOE#152]
**Write code in the preferred language and attach output with it.**

There are n projects you can attend. For each project, you know its starting and ending days and the amount of money you would get as reward. You can only attend one project during a day.

What is the maximum amount of money you can earn?

**Input**
The first input line contains an integer n: the number of projects.

After this, there are n lines. Each such line has three integers ai, bi, and pi: the starting day, the ending day, and the reward.

**Output**
Print one integer: the maximum amount of money you can earn.

**Example:**
Input:
4
2 4 4
3 6 6
6 8 2
5 7 3
Output: 7

**Comment by akanksha1131** [comment]
Can you please assign this to me? 
Akanksha Kale TY IT, Cummins
