### ISSUE TITLE
Round Trip

### ISSUE THREAD

**Issue by suryaprakashpandey** [Google-Developer-Student-Club-CCOEW/Competitive-Programming-2023-GDSC-CUMMINS-X-GDSC-MMCOE#153]
**Write code in the preferred language and attach output with it.**

Byteland has n cities and m roads between them. Your task is to design a round trip that begins in a city, goes through two or more other cities, and finally returns to the starting city. Every intermediate city on the route has to be distinct.

**Input**
The first input line has two integers n and m: the number of cities and roads. The cities are numbered 1,2,…,n.

Then, there are m lines describing the roads. Each line has two integers a and b: there is a road between those cities.

Every road is between two different cities, and there is at most one road between any two cities.

**Output**
First print an integer k: the number of cities on the route. Then print k cities in the order they will be visited. You can print any valid solution.

If there are no solutions, print "IMPOSSIBLE".

**Example**

Input:
5 6
1 3
1 2
5 3
1 5
2 4
4 5
Output:
4
3 5 1 3

**Comment by tanay-nagde** [comment]
hey please assign me this for  i can solve it

**Comment by sejalphatangare** [comment]
hi pls assign this to me
Sejal Phatangare
third year
Cummins College of Engineering,Pune.

**Comment by aditi3004** [comment]
I'm enthusiastic about contributing to this issue. May I kindly request the assignment of this issue?
-Aditi Sharma
TY CSE,CCOEW
