### ISSUE TITLE
Planets and Kingdoms

### ISSUE THREAD

**Issue by suryaprakashpandey** [Google-Developer-Student-Club-CCOEW/Competitive-Programming-2023-GDSC-CUMMINS-X-GDSC-MMCOE#155]
**Write code in the preferred language and attach output with it.**

A game has n planets, connected by m teleporters. Two planets a and b belong to the same kingdom exactly when there is a route both from a to b and from b to a. Your task is to determine for each planet its kingdom.

**Input**
The first input line has two integers n and m: the number of planets and teleporters. The planets are numbered 1,2,…,n.

After this, there are m lines describing the teleporters. Each line has two integers a and b: you can travel from planet a to planet b through a teleporter.

**Output**
First print an integer k: the number of kingdoms. After this, print for each planet a kingdom label between 1 and k. You can print any valid solution.

**Example:**

Input:
5 6
1 2
2 3
3 1
3 4
4 5
5 4
Output:
2
1 1 1 2 2

**Comment by yuziahaque** [comment]
Hi, I want to contribute.

**Comment by DhritiSoni4** [comment]
Hi! I would like to contribute

**Comment by aditi3004** [comment]
I'm enthusiastic about contributing to this issue. May I kindly request the assignment of this issue?
-Aditi Sharma
TY CSE,CCOEW
