### ISSUE TITLE
Search in Rotated Sorted Array

### ISSUE THREAD

**Issue by saakshii12** [Google-Developer-Student-Club-CCOEW/Competitive-Programming-2023-GDSC-CUMMINS-X-GDSC-MMCOE#16]
**Write code in the preferred language and attach output with it.**

There is an integer array nums sorted in ascending order (with distinct values).

Prior to being passed to your function, nums is possibly rotated at an unknown pivot index k (1 <= k < nums.length) such that the resulting array is [nums[k], nums[k+1], ..., nums[n-1], nums[0], nums[1], ..., nums[k-1]] (0-indexed). For example, [0,1,2,4,5,6,7] might be rotated at pivot index 3 and become [4,5,6,7,0,1,2].

**Given the array nums after the possible rotation and an integer target, return the index of target if it is in nums, or -1 if it is not in nums.**

You must write an algorithm with O(log n) runtime complexity.

**Example 1:**

Input: nums = [4,5,6,7,0,1,2], target = 0
Output: 4

**Example 2:**

Input: nums = [4,5,6,7,0,1,2], target = 3
Output: -1

**Example 3:**

Input: nums = [1], target = 0
Output: -1

**Comment by Subhashini014** [comment]
hello @saakshii12 could you please assign me this issue under Hacktoberfest.

**Comment by Swetathakare** [comment]
Hey @saakshii12 , I wish to work on this issue .Could you please assign it to me ?

Name : Sweta Thakare
Department : Computer (2nd year)

**Comment by Mani1881** [comment]
hey @saakshii12 can u please assign this issue to me.

**Comment by Tanishaclippy** [comment]
Name :Tanisha Jawale
Year:Second
email:tanisha.jawale@cumminscollege.in
UC number:UCE2022525
Branch:Computer
 
Please assign me this issue

**Comment by saakshii12** [comment]
> @Gdsc-Cummins @Sonia312 I have solved this problem earlier which was not merged #212 May I know the reason so that I can learn from my mistake I have done. Since the problem #212 is executing perfectly and I raised the Pull request 2 days ago. I request @Gdsc-Cummins @Sonia312 to solve my confusion
As you can see in our repo 'about' only Cummins college and MMCOE college students PR will be considered as it a part of our collaboration event.
