### ISSUE TITLE
Median of Two Sorted Arrays

### ISSUE THREAD

**Issue by saakshii12** [Google-Developer-Student-Club-CCOEW/Competitive-Programming-2023-GDSC-CUMMINS-X-GDSC-MMCOE#19]
**Write code in the preferred language and attach output with it.**

**Given two sorted arrays nums1 and nums2 of size m and n respectively, return the median of the two sorted arrays.**

The overall run time complexity should be O(log (m+n)).

**Example 1:**

Input: nums1 = [1,3], nums2 = [2]
Output: 2.00000
Explanation: merged array = [1,2,3] and median is 2.

**Example 2:**

Input: nums1 = [1,2], nums2 = [3,4]
Output: 2.50000
Explanation: merged array = [1,2,3,4] and median is (2 + 3) / 2 = 2.5.

**Comment by Subhashini014** [comment]
hello @saakshii12 could you please assign me this issue.

**Comment by preeti-hatapaki** [comment]
Can you assign me this issue?
Name -> Preeti Hatapaki
SY IT
