### ISSUE TITLE
Linked List Cycle

### ISSUE THREAD

**Issue by Sonia312** [Google-Developer-Student-Club-CCOEW/Competitive-Programming-2023-GDSC-CUMMINS-X-GDSC-MMCOE#22]
**Write code in the preferred language and attach output with it.**

Given head, the head of a linked list, determine if the linked list has a cycle in it.

There is a cycle in a linked list if there is some node in the list that can be reached again by continuously following the next pointer. Internally, pos is used to denote the index of the node that tail's next pointer is connected to. Note that pos is not passed as a parameter.

Return true if there is a cycle in the linked list. Otherwise, return false.

 

**Example 1:**

<img width="227" alt="image" src="https://github.com/Google-Developer-Student-Club-CCOEW/Competitive-Programming-2023/assets/101570119/c5029783-aa01-4fe9-8b8c-4b00642bb241">

Input: head = [3,2,0,-4], pos = 1
Output: true
Explanation: There is a cycle in the linked list, where the tail connects to the 1st node (0-indexed).

**Example 2:**

<img width="108" alt="image" src="https://github.com/Google-Developer-Student-Club-CCOEW/Competitive-Programming-2023/assets/101570119/f81ae362-53d2-4345-bdb7-b38a9632df80">

Input: head = [1,2], pos = 0
Output: true
Explanation: There is a cycle in the linked list, where the tail connects to the 0th node.

**Example 3:**

<img width="35" alt="image" src="https://github.com/Google-Developer-Student-Club-CCOEW/Competitive-Programming-2023/assets/101570119/f07ff15a-901d-42c4-a1c0-b871bbe2b921">

Input: head = [1], pos = -1
Output: false
Explanation: There is no cycle in the linked list.

**Comment by iliketrains42** [comment]
Could you please assign this to me?

**Comment by hitali-khachane** [comment]
Can u please Assign me this issue
C number-UCE2021434
Name-Hitali Khachane
[hitali.khachane@cumminscollege.in](mailto:hitali.khachane@cumminscollege.in)
Cummins college of engineering pune
