### ISSUE TITLE
Longest Common Prefix

### ISSUE THREAD

**Issue by saakshii12** [Google-Developer-Student-Club-CCOEW/Competitive-Programming-2023-GDSC-CUMMINS-X-GDSC-MMCOE#24]
**Write code in the preferred language and attach output with it.**

**Write a function to find the longest common prefix string amongst an array of strings.**

If there is no common prefix, return an empty string "".

**Example 1:**

Input: strs = ["flower","flow","flight"]
Output: "fl"

**Example 2:**

Input: strs = ["dog","racecar","car"]
Output: ""
Explanation: There is no common prefix among the input strings.

**Comment by subhashree9898** [comment]
Hey @saakshii12 please assign this issue to me!

**Comment by Swetathakare** [comment]
Hey @saakshii12 , I wish to work on this issue .Could you please assign it to me ?

Name : Sweta Thakare
Department : Computer (2nd year)

**Comment by saniyadighe** [comment]
Please assign this issue to me.
Saniya Dighe
UCE2021416
TY COMP A
saniya.dighe@cumminscollege.in

**Comment by srushtikage** [comment]
Hello @saakshii12 
Please assign this issue to me I want to work on it.
Srushti Kage
UCE2022531
Cummins College of Engineering for Women
Second Year

**Comment by Pankaj4152** [comment]
Can you please assign this to me?

**Comment by Lavanyawaghulde** [comment]
@saakshii12 I would like to work on this issue. Could you assign this issue it me?
Lavanya Waghulde
UEC2022362
SY E&TC 
Cummins college of Engineering

**Comment by Lavanyawaghulde** [comment]
@Gdsc-Cummins  I have submitted solution. Could you please check.
