### ISSUE TITLE
Find the Index of the First Occurrence in a String

### ISSUE THREAD

**Issue by saakshii12** [Google-Developer-Student-Club-CCOEW/Competitive-Programming-2023-GDSC-CUMMINS-X-GDSC-MMCOE#25]
**Write code in the preferred language and attach output with it.**

### **Given two strings needle and haystack, return the index of the first occurrence of needle in haystack, or -1 if needle is not part of haystack.**

**Example 1:**

Input: haystack = "sadbutsad", needle = "sad"
Output: 0
Explanation: "sad" occurs at index 0 and 6.
The first occurrence is at index 0, so we return 0.

**Example 2:**

Input: haystack = "leetcode", needle = "leeto"
Output: -1
Explanation: "leeto" did not occur in "leetcode", so we return -1.

**Comment by iliketrains42** [comment]
Could you assign this to me

**Comment by GayatriJ-21** [comment]
Can you please Assign me this issue
Name-Gayatri Joshi
C number-UCE2021430
gayatri.joshi@cumminscollege.in
joshigayatri716@gmail.com (github)
TY Comp
Cummins college of engineering Pune
