### ISSUE TITLE
Excel Sheet Column Title

### ISSUE THREAD

**Issue by saakshii12** [Google-Developer-Student-Club-CCOEW/Competitive-Programming-2023-GDSC-CUMMINS-X-GDSC-MMCOE#26]
**Write code in the preferred language and attach output with it.**

### **Given an integer columnNumber, return its corresponding column title as it appears in an Excel sheet.**

For example:

A -> 1
B -> 2
C -> 3
...
Z -> 26
AA -> 27
AB -> 28 
...

**Example 1:**

Input: columnNumber = 1
Output: "A"

**Example 2:**

Input: columnNumber = 28
Output: "AB"

**Example 3:**

Input: columnNumber = 701
Output: "ZY"

**Comment by Daksha0403** [comment]
Can u please Assign me this issue
Name-Daksha Kulkarni
C number-UCE2021437
[daksha.kulkarni@cumminscollege.in]
[dakshakulkarni04@gmail.com] (github)
TY Comp
Cummins college of engineering pune
