### ISSUE TITLE
Repeated Substring Pattern

### ISSUE THREAD

**Issue by saakshii12** [Google-Developer-Student-Club-CCOEW/Competitive-Programming-2023-GDSC-CUMMINS-X-GDSC-MMCOE#29]
**Write code in the preferred language and attach output with it.**

**Given a string s, check if it can be constructed by taking a substring of it and appending multiple copies of the substring together.**

**Example 1:**

Input: s = "abab"
Output: true
Explanation: It is the substring "ab" twice.

**Example 2:**

Input: s = "aba"
Output: false

**Example 3:**

Input: s = "abcabcabcabc"
Output: true
Explanation: It is the substring "abc" four times or the substring "abcabc" twice.

**Comment by Srush2823** [comment]
Can u please Assign me this issue
Name-Srushti Johari
C number-UCE2021429
[srushti.johari@cumminscollege.in]
[srush2823@gmail.com](github)
TY Comp
Cummins college of engineering pune
