### ISSUE TITLE
Majority Element

### ISSUE THREAD

**Issue by saakshii12** [Google-Developer-Student-Club-CCOEW/Competitive-Programming-2023-GDSC-CUMMINS-X-GDSC-MMCOE#3]
**Write code in the preferred language and attach output with it.**
### 
**Given an array nums of size n, return the majority element.**

The majority element is the element that appears more than ⌊n / 2⌋ times. You may assume that the majority element always exists in the array.

 

**Example 1:**

Input: nums = [3,2,3]
Output: 3

**Example 2:**

Input: nums = [2,2,1,1,1,2,2]
Output: 2

**Comment by subhashree9898** [comment]
Hey @saakshii12 please assign this issue to me!

**Comment by Subhashini014** [comment]
hello @saakshii12 could you please assign me this issue.

**Comment by RiRa25** [comment]
Can you please assign this issue to me?
Name- Richa Rathi
email - richa.rathi@cumminscollege.in
Cnumber - UEC2022324
Branch - ENTC
Year - SY

**Comment by Mani1881** [comment]
hey @saakshii12 can u please assign this issue to me.
