### ISSUE TITLE
Buddy Strings

### ISSUE THREAD

**Issue by saakshii12** [Google-Developer-Student-Club-CCOEW/Competitive-Programming-2023-GDSC-CUMMINS-X-GDSC-MMCOE#30]
**Write code in the preferred language and attach output with it.**

### **Given two strings s and goal, return true if you can swap two letters in s so the result is equal to goal, otherwise, return false.**

Swapping letters is defined as taking two indices i and j (0-indexed) such that i != j and swapping the characters at s[i] and s[j].

For example, swapping at indices 0 and 2 in "abcd" results in "cbad".
 
**Example 1:**

Input: s = "ab", goal = "ba"
Output: true
Explanation: You can swap s[0] = 'a' and s[1] = 'b' to get "ba", which is equal to goal.

**Example 2:**

Input: s = "ab", goal = "ab"
Output: false
Explanation: The only letters you can swap are s[0] = 'a' and s[1] = 'b', which results in "ba" != goal.

**Example 3:**

Input: s = "aa", goal = "aa"
Output: true
Explanation: You can swap s[0] = 'a' and s[1] = 'a' to get "aa", which is equal to goal.

**Comment by MrImmortal09** [comment]
Hey I would like to work on this.

**Comment by MrImmortal09** [comment]
> Hey I would like to work on this.

Pls Assign me

**Comment by harshraj8843** [comment]
Hey @saakshii12 

You can use `assign-me` bot to auto-assign issues to new contributors

App Link : https://github.com/marketplace/assign-me
Repo Link : https://github.com/ilihub/assign-me
Create Test Issue : https://github.com/ilihub/holy-moly/issues/new?assignees=&labels=test+assign+me+bot&projects=&template=test-assign-me.yml&title=Test+Issue

**Comment by Subhashini014** [comment]
hey @saakshii12 could you please assign me this issue.

**Comment by saniyadighe** [comment]
Please assign this issue to me
Saniya Dighe
UCE2021416
TY COMP A
[saniya.dighe@cumminscollege.in](mailto:saniya.dighe@cumminscollege.in)
