### ISSUE TITLE
Minimum Remove to Make Valid Parentheses

### ISSUE THREAD

**Issue by saakshii12** [Google-Developer-Student-Club-CCOEW/Competitive-Programming-2023-GDSC-CUMMINS-X-GDSC-MMCOE#31]
**Write code in the preferred language and attach output with it.**

**Given a string s of '(' , ')' and lowercase English characters.**

**Your task is to remove the minimum number of parentheses ( '(' or ')', in any positions ) so that the resulting parentheses string is valid and return any valid string.**

Formally, a parentheses string is valid if and only if:

It is the empty string, contains only lowercase characters, or
It can be written as AB (A concatenated with B), where A and B are valid strings, or
It can be written as (A), where A is a valid string.
 
**Example 1:**

Input: s = "lee(t(c)o)de)"
Output: "lee(t(c)o)de"
Explanation: "lee(t(co)de)" , "lee(t(c)ode)" would also be accepted.

**Example 2:**

Input: s = "a)b(c)d"
Output: "ab(c)d"

**Example 3:**

Input: s = "))(("
Output: ""
Explanation: An empty string is also valid.

**Comment by Priyanshu229** [comment]
Hey @saakshii12 @Sonia312 
Please assign this issue to me.

**Comment by Daksha0403** [comment]
Can u please Assign me this issue
Name-Daksha Kulkarni
C number-UCE2021437
[daksha.kulkarni@cumminscollege.in]
[dakshakulkarni04@gmail.com] (github)
TY Comp
Cummins college of engineering pune
