### ISSUE TITLE
Longest Palindromic Substring

### ISSUE THREAD

**Issue by saakshii12** [Google-Developer-Student-Club-CCOEW/Competitive-Programming-2023-GDSC-CUMMINS-X-GDSC-MMCOE#32]
**Write code in the preferred language and attach output with it.**

### **Given a string s, return the longest palindromic substring in s.**

**Example 1:**

Input: s = "babad"
Output: "bab"
Explanation: "aba" is also a valid answer.

**Example 2:**

Input: s = "cbbd"
Output: "bb"

**Comment by DhritiSoni4** [comment]
Hi! I would like to contribute!

**Comment by Swetathakare** [comment]
Hey @saakshii12 , I wish to work on this issue .Could you please assign it to me ?

Name : Sweta Thakare
Department : Computer (2nd year)

**Comment by schauna7** [comment]
i would like to work on this issue,
name:Schauna singh
SY IT UIT2022860
