### ISSUE TITLE
Zigzag Conversion

### ISSUE THREAD

**Issue by saakshii12** [Google-Developer-Student-Club-CCOEW/Competitive-Programming-2023-GDSC-CUMMINS-X-GDSC-MMCOE#34]
**Write code in the preferred language and attach output with it.**

The string "PAYPALISHIRING" is written in a zigzag pattern on a given number of rows like this: (you may want to display this pattern in a fixed font for better legibility)

P   A   H   N
A P L S I I G
Y   I   R
And then read line by line: "PAHNAPLSIIGYIR"

**Write the code that will take a string and make this conversion given a number of rows:**
**string convert(string s, int numRows);**
 
**Example 1:**

Input: s = "PAYPALISHIRING", numRows = 3
Output: "PAHNAPLSIIGYIR"

**Example 2:**

Input: s = "PAYPALISHIRING", numRows = 4
Output: "PINALSIGYAHRPI"
Explanation:
P     I    N
A   L S  I G
Y A   H R
P     I

**Example 3:**

Input: s = "A", numRows = 1
Output: "A"

**Comment by varunchopra-08** [comment]
@saakshii12 i would love to contribute do assign me this issue ..
