### ISSUE TITLE
Longest Substring Without Repeating Characters

### ISSUE THREAD

**Issue by saakshii12** [Google-Developer-Student-Club-CCOEW/Competitive-Programming-2023-GDSC-CUMMINS-X-GDSC-MMCOE#35]
**Write code in the preferred language and attach output with it.**

 ### **Given a string s, find the length of the longest substring without repeating characters.**

**Example 1:**

Input: s = "abcabcbb"
Output: 3
Explanation: The answer is "abc", with the length of 3.

**Example 2:**

Input: s = "bbbbb"
Output: 1
Explanation: The answer is "b", with the length of 1.

**Example 3:**

Input: s = "pwwkew"
Output: 3
Explanation: The answer is "wke", with the length of 3.
Notice that the answer must be a substring, "pwke" is a subsequence and not a substring.

**Comment by Subhashini014** [comment]
hello @saakshii12 could you please assign me this issue.

**Comment by anu-shka-k** [comment]
Hi @saakshii12, could you please assign this issue to me?

Anushka Kulkarni
SY EnTC
anushka.y.kulkarni@cumminscollege.in

**Comment by anu-shka-k** [comment]
I will not be able to contribute to this issue. Sorry for the inconvinience.

**Comment by rhuchasant** [comment]
Hi @saakshii12 , I wish to work on this. Please assign it to me.
Rhucha Sant
TY Comp, CCOEW

**Comment by Lavanyawaghulde** [comment]
@Gdsc-Cummins Could you assign this issue to me ?
Name : Lavanya Waghulde
Roll no :UCE2022362
e.mail : lavanya.waghulde@cumminscollege.in
