### ISSUE TITLE
Palindrome Linked List

### ISSUE THREAD

**Issue by Sonia312** [Google-Developer-Student-Club-CCOEW/Competitive-Programming-2023-GDSC-CUMMINS-X-GDSC-MMCOE#36]
**Write code in the preferred language and attach output with it.**

Given the head of a singly linked list, return true if it is a 
palindrome
 or false otherwise.

 

**Example 1:**

<img width="317" alt="image" src="https://github.com/Google-Developer-Student-Club-CCOEW/Competitive-Programming-2023/assets/101570119/d8732b3a-1d38-4c97-a0f7-ea7af75f10d8">

Input: head = [1,2,2,1]
Output: true

**Example 2:**

<img width="137" alt="image" src="https://github.com/Google-Developer-Student-Club-CCOEW/Competitive-Programming-2023/assets/101570119/58d9ebb3-53da-42d8-a85d-6c70c5a2f172">

Input: head = [1,2]
Output: false

**Comment by maskboyAvi** [comment]
@Sonia312 I want to work on this issue. Please assign it to me.

**Comment by Swamini11** [comment]
Can u please Assign me this issue
Name-Swamini Bhagwat
C number-UCE2021403
[swamini.bhagwat@cumminscollege.in](mailto:swamini.bhagwat@cumminscollege.in)
[swaminibhagwat11@gmail.com](mailto:swaminibhagwat11@gmail.com) (github)
TY Comp
Cummins college of engineering pune
