### ISSUE TITLE
Squares of a Sorted Array

### ISSUE THREAD

**Issue by saakshii12** [Google-Developer-Student-Club-CCOEW/Competitive-Programming-2023-GDSC-CUMMINS-X-GDSC-MMCOE#4]
**Write code in the preferred language and attach output with it.**

**Given an integer array nums sorted in non-decreasing order, return an array of the squares of each number sorted in non-decreasing order.**

**Example 1:**

Input: nums = [-4,-1,0,3,10]
Output: [0,1,9,16,100]
Explanation: After squaring, the array becomes [16,1,0,9,100].
After sorting, it becomes [0,1,9,16,100].

**Example 2:**

Input: nums = [-7,-3,2,3,11]
Output: [4,9,9,49,121]

**Comment by Sam-bhav-20** [comment]
@saakshii12 kindly assign me this issue under hacktoberfest

**Comment by ankitmwd01** [comment]
please assign me this task

**Comment by Mani1881** [comment]
hey @saakshii12  can u please assign this issue to me.

**Comment by srushtikage** [comment]
Hello
Please assign this issue to me I want to work on it.
Srushti Kage
UCE2022531
Cummins College of Engineering for Women
Second Year

**Comment by srushtikage** [comment]
Can u please check and merge my code, so that I can work on the next issue.

**Comment by srushtikage** [comment]
While creating the pull request my main branch got compared and the median of sorted arrays  code also got added which was there  in my main branch of forked repo along with the square of sorted array code Please take into consideration the square of sorted array Code File only while checking. I'll keep in mind that next time it does not happen.
Thank you.
