### ISSUE TITLE
Distinct Subsequences

### ISSUE THREAD

**Issue by saakshii12** [Google-Developer-Student-Club-CCOEW/Competitive-Programming-2023-GDSC-CUMMINS-X-GDSC-MMCOE#40]
**Write code in the preferred language and attach output with it.**

### **Given two strings s and t, return the number of distinct subsequences of s which equals t.**

The test cases are generated so that the answer fits on a 32-bit signed integer.

**Example 1:**

Input: s = "rabbbit", t = "rabbit"
Output: 3
Explanation:
As shown below, there are 3 ways you can generate "rabbit" from s.
rabbbit
rabbbit
rabbbit

**Example 2:**

Input: s = "babgbag", t = "bag"
Output: 5
Explanation:
As shown below, there are 5 ways you can generate "bag" from s.
babgbag
babgbag
babgbag
babgbag
babgbag

**Comment by Surajkumar5050** [comment]
Hey @saakshii12 , I can solve this Issue. Please assign to me. Thanks!

**Comment by Mansiprajapatii** [comment]
hey @saakshii12 
i want to solve this issue. Can you assign it to me. Thanks!
