### ISSUE TITLE
Rotate List

### ISSUE THREAD

**Issue by Sonia312** [Google-Developer-Student-Club-CCOEW/Competitive-Programming-2023-GDSC-CUMMINS-X-GDSC-MMCOE#41]
**Write code in the preferred language and attach output with it.**

Given the head of a linked list, rotate the list to the right by k places.

 

**Example 1:**

<img width="338" alt="image" src="https://github.com/Google-Developer-Student-Club-CCOEW/Competitive-Programming-2023/assets/101570119/1d525cd7-ec83-4da4-9606-8e82b5369993">

Input: head = [1,2,3,4,5], k = 2
Output: [4,5,1,2,3]

**Example 2:**

<img width="228" alt="image" src="https://github.com/Google-Developer-Student-Club-CCOEW/Competitive-Programming-2023/assets/101570119/a7435aaa-c326-4a65-8b2b-4972419a3537">

Input: head = [0,1,2], k = 4
Output: [2,0,1]

**Comment by stktyagi** [comment]
hello, I want to contribute and resolve this issue for the hacktoberfest. Can you assign me this issue please. Thanks a lot!

**Comment by janhavibagret** [comment]
Can you please assign me this issue? I would like to work on it.
