### ISSUE TITLE
Strange Printer

### ISSUE THREAD

**Issue by saakshii12** [Google-Developer-Student-Club-CCOEW/Competitive-Programming-2023-GDSC-CUMMINS-X-GDSC-MMCOE#43]
**Write code in the preferred language and attach output with it.**

There is a strange printer with the following two special properties:

The printer can only print a sequence of the same character each time.
At each turn, the printer can print new characters starting from and ending at any place and will cover the original existing characters.

### **Given a string s, return the minimum number of turns the printer needed to print it.**

**Example 1:**

Input: s = "aaabbb"
Output: 2
Explanation: Print "aaa" first and then print "bbb".

**Example 2:**

Input: s = "aba"
Output: 2
Explanation: Print "aaa" first and then print "b" from the second place of the string, which will cover the existing character 'a'.

**Comment by RishabhDhawad** [comment]
I would like to work on this, can you assign me this issue?

**Comment by Mansiprajapatii** [comment]
hey @saakshii12 
I want to solve this issue. Can you assign me this issue. Thank!!
