### ISSUE TITLE
Implement Stack using Queues

### ISSUE THREAD

**Issue by saakshii12** [Google-Developer-Student-Club-CCOEW/Competitive-Programming-2023-GDSC-CUMMINS-X-GDSC-MMCOE#46]
**Write code in the preferred language and attach output with it.**

### **Implement a last-in-first-out (LIFO) stack using only two queues. The implemented stack should support all the functions of a normal stack (push, top, pop, and empty).**

Implement the MyStack class:

void push(int x) Pushes element x to the top of the stack.
int pop() Removes the element on the top of the stack and returns it.
int top() Returns the element on the top of the stack.
boolean empty() Returns true if the stack is empty, false otherwise.

Notes:
You must use only standard operations of a queue, which means that only push to back, peek/pop from front, size and is empty operations are valid.
Depending on your language, the queue may not be supported natively. You may simulate a queue using a list or deque (double-ended queue) as long as you use only a queue's standard operations.
 

**Example 1:**

Input
["MyStack", "push", "push", "top", "pop", "empty"]
[[], [1], [2], [], [], []]

Output
[null, null, null, 2, 2, false]

Explanation
MyStack myStack = new MyStack();
myStack.push(1);
myStack.push(2);
myStack.top(); // return 2
myStack.pop(); // return 2
myStack.empty(); // return False

**Comment by krishna16sharma** [comment]
Hi @saakshii12 can I take this up? Thanks!

**Comment by Subhashini014** [comment]
hello @saakshii12 could you assign me this issue.

**Comment by GayatriJ-21** [comment]
Can you please Assign me this issue
Name-Gayatri Joshi
C number-UCE2021430
gayatri.joshi@cumminscollege.in
joshigayatri716@gmail.com (github)
TY Comp
Cummins college of engineering pune
