### ISSUE TITLE
Remove Duplicates from Sorted Array

### ISSUE THREAD

**Issue by saakshii12** [Google-Developer-Student-Club-CCOEW/Competitive-Programming-2023-GDSC-CUMMINS-X-GDSC-MMCOE#5]
**Write code in the preferred language and attach output with it.**

**Given an integer array nums sorted in non-decreasing order, remove the duplicates [in-place](https://en.wikipedia.org/wiki/In-place_algorithm) such that each unique element appears only once. The relative order of the elements should be kept the same. Then return the number of unique elements in nums.**

Consider the number of unique elements of nums to be k, to get accepted, you need to do the following things:

Change the array nums such that the first k elements of nums contain the unique elements in the order they were present in nums initially. The remaining elements of nums are not important as well as the size of nums.
Return k.

**Example 1:**

Input: nums = [1,1,2]
Output: 2, nums = [1,2,_]
Explanation: Your function should return k = 2, with the first two elements of nums being 1 and 2 respectively.
It does not matter what you leave beyond the returned k (hence they are underscores).

**Example 2:**

Input: nums = [0,0,1,1,1,2,2,3,3,4]
Output: 5, nums = [0,1,2,3,4,_,_,_,_,_]
Explanation: Your function should return k = 5, with the first five elements of nums being 0, 1, 2, 3, and 4 respectively.
It does not matter what you leave beyond the returned k (hence they are underscores).

**Comment by iliketrains42** [comment]
Could you assign this to me?

**Comment by Subhashini014** [comment]
hello @saakshii12 could you please assign this issue to me.

**Comment by Swetathakare** [comment]
Hey @saakshii12 , I wish to work on this issue .Could you please assign it to me ?

Name : Sweta Thakare
Department : Computer (2nd year)

**Comment by NigeeHettige** [comment]
Hi,
Can you assign me to this?

**Comment by Mani1881** [comment]
hey @saakshii12 can u please assign this issue to me.

class Solution {
    public int removeDuplicates(int[] nums) {
        int i=0;
        for(int j=1;j<nums.length;j++){
            if(nums[i]!=nums[j]){
                nums[i+1]=nums[j];
                i++;
            }
        }
        return i+1;
    }
}
this is brute force solution .i can even change into optimal code.
I really want to contribute to this issue.

**Comment by vrishitagharte** [comment]
Vrishita Gharte
UEC2021128
[vrishitagharte1@gmail.com](mailto:vrishitagharte1@gmail.com)
TY ENTC
can i please work on this issue?

**Comment by Lavanyawaghulde** [comment]
@Gdsc-Cummins  Could you assign this issue to me ?
Name : Lavanya Waghulde
Roll no :UCE2022362
e.mail : lavanya.waghulde@cumminscollege.in
