### ISSUE TITLE
Reverse Linked List II

### ISSUE THREAD

**Issue by Sonia312** [Google-Developer-Student-Club-CCOEW/Competitive-Programming-2023-GDSC-CUMMINS-X-GDSC-MMCOE#51]
**Write code in the preferred language and attach output with it.**

Given the head of a singly linked list and two integers left and right where left <= right, reverse the nodes of the list from position left to position right, and return the reversed list.

 

**Example 1:**

<img width="406" alt="image" src="https://github.com/Google-Developer-Student-Club-CCOEW/Competitive-Programming-2023/assets/101570119/4f4065c5-a76d-4a9e-aeab-68384df31f77">

Input: head = [1,2,3,4,5], left = 2, right = 4
Output: [1,4,3,2,5]

**Example 2:**

Input: head = [5], left = 1, right = 1
Output: [5]

**Comment by vivekPatil45** [comment]
@Sonia312 Can you please assign this issue to me under HACKTOBERFEST

**Comment by RiRa25** [comment]
@Sonia312 Hey Sonia! Can u please assign this issue to me?
Name: Richa Rathi

**Comment by Swetathakare** [comment]
Hey @saakshii12 , I wish to work on this issue .Could you please assign it to me ?

Name : Sweta Thakare
Department : Computer (2nd year)

**Comment by Eesha04** [comment]
Name - Eesha Satvalekar
email - eesha.satvalekar@cumminscollege.in
Can you please assign this issue to me?
I would like to work on it.

**Comment by janhavibagret** [comment]
Can you please assign me this issue? I would like to work on it.
