### ISSUE TITLE
Trapping Rain Water

### ISSUE THREAD

**Issue by saakshii12** [Google-Developer-Student-Club-CCOEW/Competitive-Programming-2023-GDSC-CUMMINS-X-GDSC-MMCOE#53]
**Write code in the preferred language and attach output with it.**

### **Given n non-negative integers representing an elevation map where the width of each bar is 1, compute how much water it can trap after raining.**

**Example 1:**
![image](https://github.com/Google-Developer-Student-Club-CCOEW/Competitive-Programming-2023/assets/128240967/8e3e8317-e74f-4a72-a61c-38ed7f44533e)
Input: height = [0,1,0,2,1,0,1,3,2,1,2,1]
Output: 6
Explanation: The above elevation map (black section) is represented by array [0,1,0,2,1,0,1,3,2,1,2,1]. In this case, 6 units of rain water (blue section) are being trapped.

**Example 2:**

Input: height = [4,2,0,3,2,5]
Output: 9

**Comment by muruga21** [comment]
hey @saakshii12 can you assign this work to me ..?

**Comment by Swetathakare** [comment]
Hey @saakshii12 , I wish to work on this issue .Could you please assign it to me ?

Name : Sweta Thakare
Department : Computer (2nd year)
Roll no :UCE2022654

**Comment by Lavanyawaghulde** [comment]
@saakshii12 I would like to work on this issue. Could you assign this issue it me?
Lavanya Waghulde
UEC2022362
SY E&TC 
Cummins college of Engineering

**Comment by Lavanyawaghulde** [comment]
@Gdsc-Cummins I have submitted the solution Could you please check
