### ISSUE TITLE
Kth Largest Element in an Array

### ISSUE THREAD

**Issue by saakshii12** [Google-Developer-Student-Club-CCOEW/Competitive-Programming-2023-GDSC-CUMMINS-X-GDSC-MMCOE#57]
**Write code in the preferred language and attach output with it.**

### **Given an integer array nums and an integer k, return the kth largest element in the array.**

_Note that it is the kth largest element in the sorted order, not the kth distinct element._

Can you solve it without sorting?

**Example 1:**

Input: nums = [3,2,1,5,6,4], k = 2
Output: 5

**Example 2:**

Input: nums = [3,2,3,1,2,4,5,5,6], k = 4
Output: 4

**Comment by aniketsinha620** [comment]
Hey @saakshii12 , please assign me this problem

**Comment by Subhashini014** [comment]
Hello @sakshii12 could you please assign me this issue as I am currently preparing data structures and algorithms using java Ican definitely do this problem.

**Comment by hitali-khachane** [comment]
Can u please Assign me this issue
C number-UCE2021434
Name-Hitali Khachane
[hitali.khachane@cumminscollege.in](mailto:hitali.khachane@cumminscollege.in)
Cummins college of engineering pune

**Comment by RiRa25** [comment]
Can you please assign this issue to me?
Name- Richa Rathi
email - richa.rathi@cumminscollege.in
Cnumber - UEC2022324
Branch - ENTC
Year - SY

**Comment by Tanishaclippy** [comment]
Can you assign me this issue ??
Name:Tanisha Jawale
email:tanisha.jawale@cumminscollege.in
Cnumber:UCE2022525
Branch:Computer
Year:SY

**Comment by Mani1881** [comment]
hey @saakshii12 can u please assign this issue to me.

**Comment by srushtikage** [comment]
Hello @saakshii12 
Please assign this issue to me I want to work on it.
Srushti Kage
UCE2022531
Cummins College of Engineering for Women
Second Year
