### ISSUE TITLE
K-th Smallest Prime Fraction

### ISSUE THREAD

**Issue by saakshii12** [Google-Developer-Student-Club-CCOEW/Competitive-Programming-2023-GDSC-CUMMINS-X-GDSC-MMCOE#58]
**Write code in the preferred language and attach output with it.**

### **You are given a sorted integer array arr containing 1 and prime numbers, where all the integers of arr are unique. You are also given an integer k.**

For every i and j where 0 <= i < j < arr.length, we consider the fraction arr[i] / arr[j].

Return the kth smallest fraction considered. Return your answer as an array of integers of size 2, where answer[0] == arr[i] and answer[1] == arr[j].

**Example 1:**

Input: arr = [1,2,3,5], k = 3
Output: [2,5]
Explanation: The fractions to be considered in sorted order are:
1/5, 1/3, 2/5, 1/2, 3/5, and 2/3.
The third fraction is 2/5.

**Example 2:**

Input: arr = [1,7], k = 1
Output: [1,7]

**Comment by Daksha0403** [comment]
Can u please Assign me this issue
Name-Daksha Kulkarni
C number-UCE2021437
[daksha.kulkarni@cumminscollege.in]
[dakshakulkarni04@gmail.com] (github)
TY Comp
Cummins college of engineering pune
