### ISSUE TITLE
Search Insert Position

### ISSUE THREAD

**Issue by saakshii12** [Google-Developer-Student-Club-CCOEW/Competitive-Programming-2023-GDSC-CUMMINS-X-GDSC-MMCOE#6]
**Write code in the preferred language and attach output with it.**

**Given a sorted array of distinct integers and a target value, return the index if the target is found. If not, return the index where it would be if it were inserted in order.**

You must write an algorithm with O(log n) runtime complexity.

**Example 1:**

Input: nums = [1,3,5,6], target = 5
Output: 2

**Example 2:**

Input: nums = [1,3,5,6], target = 2
Output: 1

**Example 3:**

Input: nums = [1,3,5,6], target = 7
Output: 4

**Comment by MOHIT-PANDEY215** [comment]
Hey @saakshii12, Please assign this issue to me.

**Comment by Tanishaclippy** [comment]
Name:Tanisha Jawale
Year:2nd comp
Email:tanisha.jawale@cumminscollege.in


Please assign me this issue
