### ISSUE TITLE
Reverse a sublist of a linked list

### ISSUE THREAD

**Issue by Sonia312** [Google-Developer-Student-Club-CCOEW/Competitive-Programming-2023-GDSC-CUMMINS-X-GDSC-MMCOE#60]
**Write code in the preferred language and attach output with it.**

Given a linked list and positions m and n. Reverse the linked list from position m to n.

**Example 1:**

Input :
N = 10
Linked List = 1->7->5->3->9->8->10
                      ->2->2->5->NULL
m = 1, n = 8
Output : 2 10 8 9 3 5 7 1 2 5 
Explanation :
The nodes from position 1 to 8 
are reversed, resulting in 
2 10 8 9 3 5 7 1 2 5.

**Example 2:**

Input:
N = 6
Linked List = 1->2->3->4->5->6->NULL
m = 2, n = 4
Output: 1 4 3 2 5 6
Explanation:
Nodes from position 2 to 4 
are reversed resulting in
1 4 3 2 5 6.
Your task :
You don't need to read input or print anything. Your task is to complete the function reverseBetween() which takes the head of the linked list and two integers m and n as input and returns the head of the new linked list after reversing the nodes from position m to n.
 
Expected Time Complexity: O(N)
Expected Auxiliary Space: O(1)

**Comment by schauna7** [comment]
i have created pull request for this issue please review it

**Comment by suryaprakashpandey** [comment]
> i have created pull request for this issue please review it

Hey @schauna7! I've checked your pull request, and I'd like you to focus on completing the `reverseBetween()` function. Instead of providing the entire code, please create a function that follows the given parameters. You can use this template:

```java

/*
 * Definition for singly-linked list.
 * public class ListNode {
 *     int val;
 *     ListNode next;
 *     ListNode() {}
 *     ListNode(int val) { this.val = val; }
 *     ListNode(int val, ListNode next) { this.val = val; this.next = next; }
 * }
 */

class Solution {
    public ListNode reverseBetween(ListNode head, int left, int right) {
        // Write your code here
    }
}
```

**Comment by schauna7** [comment]
> > i have created pull request for this issue please review it
> 
> Hey @schauna7! I've checked your pull request, and I'd like you to focus on completing the `reverseBetween()` function. Instead of providing the entire code, please create a function that follows the given parameters. You can use this template:
> 
> ```java
> /*
>  * Definition for singly-linked list.
>  * public class ListNode {
>  *     int val;
>  *     ListNode next;
>  *     ListNode() {}
>  *     ListNode(int val) { this.val = val; }
>  *     ListNode(int val, ListNode next) { this.val = val; this.next = next; }
>  * }
>  */
> 
> class Solution {
>     public ListNode reverseBetween(ListNode head, int left, int right) {
>         // Write your code here
>     }
> }
> ```

Ok sure I'll work on the changes as suggested and will let you know when done. Thank you for your feedback.

**Comment by schauna7** [comment]
I have made the changes please review it.
