### ISSUE TITLE
All Nodes Distance K in Binary Tree

### ISSUE THREAD

**Issue by Sonia312** [Google-Developer-Student-Club-CCOEW/Competitive-Programming-2023-GDSC-CUMMINS-X-GDSC-MMCOE#71]
**Write code in the preferred language and attach output with it.**

Given the root of a binary tree, the value of a target node target, and an integer k, return an array of the values of all nodes that have a distance k from the target node.

You can return the answer in any order.

 

**Example 1:**

<img width="369" alt="image" src="https://github.com/Google-Developer-Student-Club-CCOEW/Competitive-Programming-2023/assets/101570119/340e6422-5e0a-43b4-bf66-d99e5b7848ee">

Input: root = [3,5,1,6,2,0,8,null,null,7,4], target = 5, k = 2
Output: [7,4,1]
Explanation: The nodes that are a distance 2 from the target node (with value 5) have values 7, 4, and 1.

**Example 2:**

Input: root = [1], target = 1, k = 3
Output: []

**Comment by Swetathakare** [comment]
Hey @saakshii12 , I wish to work on this issue .Could you please assign it to me ?
Name          : Sweta Thakare
Department : Computer (2nd year)
Roll no         :UCE2022654

**Comment by bargeshreeya** [comment]
hey @Sonia312 if this issue isn't solved yet , i'd like to contribute 
if you could assign it to me ?
Roll no: UIT2021810
