### ISSUE TITLE
Find the Difference

### ISSUE THREAD

**Issue by saakshii12** [Google-Developer-Student-Club-CCOEW/Competitive-Programming-2023-GDSC-CUMMINS-X-GDSC-MMCOE#72]
**Write code in the preferred language and attach output with it.**

You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.

**Example 1:**

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.

**Example 2:**

Input: s = "", t = "y"
Output: "y"

**Comment by Priyanshu229** [comment]
Hey @saakshii12
Please assign this issue to me.

**Comment by Subhashini014** [comment]
Hey @saakshii12 Could you please assign me this issue currently I am preparing Data Structures and algorithms using Java and I can improve my Coding skills and I would be very thankful to you if you assign me this issue.

**Comment by Pankaj4152** [comment]
Can you please assign this to me?
