### ISSUE TITLE
All Possible Full Binary Trees

### ISSUE THREAD

**Issue by Sonia312** [Google-Developer-Student-Club-CCOEW/Competitive-Programming-2023-GDSC-CUMMINS-X-GDSC-MMCOE#73]
**Write code in the preferred language and attach output with it.**

Given an integer n, return a list of all possible full binary trees with n nodes. Each node of each tree in the answer must have Node.val == 0.

Each element of the answer is the root node of one possible tree. You may return the final list of trees in any order.

A full binary tree is a binary tree where each node has exactly 0 or 2 children.

 

**Example 1:**

<img width="429" alt="image" src="https://github.com/Google-Developer-Student-Club-CCOEW/Competitive-Programming-2023/assets/101570119/7fc5d79e-72b8-4670-96cc-7359fe75d4d7">

Input: n = 7
Output: [[0,0,0,null,null,0,0,null,null,0,0],[0,0,0,null,null,0,0,0,0],[0,0,0,0,0,0,0],[0,0,0,0,0,null,null,null,null,0,0],[0,0,0,0,0,null,null,0,0]]

**Example 2:**

Input: n = 3
Output: [[0,0,0]]

**Comment by RishabhDhawad** [comment]
I would like to work on this, can you assign me this issue?
