### ISSUE TITLE
Count Good Nodes in Binary Tree

### ISSUE THREAD

**Issue by Sonia312** [Google-Developer-Student-Club-CCOEW/Competitive-Programming-2023-GDSC-CUMMINS-X-GDSC-MMCOE#75]
**Write code in the preferred language and attach output with it.**

Given a binary tree root, a node X in the tree is named good if in the path from root to X there are no nodes with a value greater than X.

Return the number of good nodes in the binary tree.

 

**Example 1:**

<img width="195" alt="image" src="https://github.com/Google-Developer-Student-Club-CCOEW/Competitive-Programming-2023/assets/101570119/be6820de-b100-4cba-8f63-f3805e81e20f">

Input: root = [3,1,4,3,null,1,5]
Output: 4
Explanation: Nodes in blue are good.
Root Node (3) is always a good node.
Node 4 -> (3,4) is the maximum value in the path starting from the root.
Node 5 -> (3,4,5) is the maximum value in the path
Node 3 -> (3,1,3) is the maximum value in the path.

**Example 2:**

<img width="118" alt="image" src="https://github.com/Google-Developer-Student-Club-CCOEW/Competitive-Programming-2023/assets/101570119/5be51b7a-e7ec-4340-9c32-8f8ac12b3081">

Input: root = [3,3,null,4,2]
Output: 3
Explanation: Node 2 -> (3, 3, 2) is not good, because "3" is higher than it.

**Example 3:**

Input: root = [1]
Output: 1
Explanation: Root is considered as good.

**Comment by aniketsinha620** [comment]
Hey @Sonia312 , please assign me this problem

**Comment by anu-shka-k** [comment]
Hi @Sonia312 , Could you assign this issue to me?
- Anushka Kulkarni
  SY EnTC Cummins

**Comment by anu-shka-k** [comment]
I will not be able to contribute to this issue. Sorry for the inconvinience.

**Comment by bhairavibhuyar** [comment]
Hello, I would like to work on this issue. Can you please assign it to me?
Name - Bhairavi Bhuyar
Year - Third Year
College - CCOEW, Pune
