### ISSUE TITLE
Letter Combinations of a Phone Number

### ISSUE THREAD

**Issue by saakshii12** [Google-Developer-Student-Club-CCOEW/Competitive-Programming-2023-GDSC-CUMMINS-X-GDSC-MMCOE#77]
**Write code in the preferred language and attach output with it.**

### **Given a string containing digits from 2-9 inclusive, return all possible letter combinations that the number could represent. Return the answer in any order.**

A mapping of digits to letters (just like on the telephone buttons) is given below. Note that 1 does not map to any letters.
![image](https://github.com/Google-Developer-Student-Club-CCOEW/Competitive-Programming-2023/assets/128240967/812f4b42-28ca-4b58-a65a-876a519ae1e7)

**Example 1:**

Input: digits = "23"
Output: ["ad","ae","af","bd","be","bf","cd","ce","cf"]

**Example 2:**

Input: digits = ""
Output: []

**Example 3:**

Input: digits = "2"
Output: ["a","b","c"]

**Comment by Ashani-Sansala** [comment]
can you assign me this issue ?

**Comment by bhairavibhuyar** [comment]
Hello, I would like to work on this issue. Can you please assign it to me?
Name - Bhairavi Bhuyar
Year - Third Year
College - CCOEW, Pune
