### ISSUE TITLE
Reorganize String

### ISSUE THREAD

**Issue by saakshii12** [Google-Developer-Student-Club-CCOEW/Competitive-Programming-2023-GDSC-CUMMINS-X-GDSC-MMCOE#79]
**Write code in the preferred language and attach output with it.**

### **Given a string s, rearrange the characters of s so that any two adjacent characters are not the same.**

Return any possible rearrangement of s or return "" if not possible.

**Example 1:**

Input: s = "aab"
Output: "aba"

**Example 2:**

Input: s = "aaab"
Output: ""

**Comment by MOHIT-PANDEY215** [comment]
Hey @saakshii12 please assign this issue to me.

**Comment by srushtikage** [comment]
Hello
Please assign this issue to me I want to work on it.
Srushti Kage
UCE2022531
Cummins College of Engineering for Women
Second Year
