### ISSUE TITLE
Product of Array Except Self

### ISSUE THREAD

**Issue by saakshii12** [Google-Developer-Student-Club-CCOEW/Competitive-Programming-2023-GDSC-CUMMINS-X-GDSC-MMCOE#8]
**Write code in the preferred language and attach output with it.**

**Given an integer array nums, return an array answer such that answer[i] is equal to the product of all the elements of nums except nums[i].**

The product of any prefix or suffix of nums is guaranteed to fit in a 32-bit integer.

You must write an algorithm that runs in O(n) time and without using the division operation.

**Example 1:**

Input: nums = [1,2,3,4]
Output: [24,12,8,6]

**Example 2:**

Input: nums = [-1,1,0,-3,3]
Output: [0,0,9,0,0]

**Comment by iliketrains42** [comment]
Could you assign this to me?

**Comment by Subhashini014** [comment]
hello saakshii12 could you please assign me this issue.

**Comment by Daksha0403** [comment]
Can u please Assign me this issue
Name-Daksha Kulkarni
C number-UCE2021437
[daksha.kulkarni@cumminscollege.in]
[dakshakulkarni04@gmail.com] (github)
TY Comp
Cummins college of engineering pune
