### ISSUE TITLE
Top K Frequent Elements

### ISSUE THREAD

**Issue by saakshii12** [Google-Developer-Student-Club-CCOEW/Competitive-Programming-2023-GDSC-CUMMINS-X-GDSC-MMCOE#81]
**Write code in the preferred language and attach output with it.**

### **Given an integer array nums and an integer k, return the k most frequent elements. You may return the answer in any order.**

**Example 1:**

Input: nums = [1,1,1,2,2,3], k = 2
Output: [1,2]

**Example 2:**

Input: nums = [1], k = 1
Output: [1]

**Comment by iliketrains42** [comment]
Could you assign this to me?

**Comment by aniketsinha620** [comment]
Hey @saakshii12 could you, please assign me this problem.

**Comment by Pankaj4152** [comment]
Can you please assign this to me?

**Comment by Eesha04** [comment]
Name - Eesha Satvalekar 
email-eesha.satvalekar@cumminscollege.in
Can you please assign this issue to me?
