### ISSUE TITLE
Sudoku Solver

### ISSUE THREAD

**Issue by saakshii12** [Google-Developer-Student-Club-CCOEW/Competitive-Programming-2023-GDSC-CUMMINS-X-GDSC-MMCOE#82]
**Write code in the preferred language and attach output with it.**

### **Write a program to solve a Sudoku puzzle by filling the empty cells.**

A sudoku solution must satisfy all of the following rules:

1. Each of the digits 1-9 must occur exactly once in each row.
2. Each of the digits 1-9 must occur exactly once in each column.
3. Each of the digits 1-9 must occur exactly once in each of the 9 3x3 sub-boxes of the grid.
The '.' character indicates empty cells.

**Example 1:**
![image](https://github.com/Google-Developer-Student-Club-CCOEW/Competitive-Programming-2023/assets/128240967/196fdadb-4e4a-4375-9769-1d732e18056e)
Input: board = [["5","3",".",".","7",".",".",".","."],["6",".",".","1","9","5",".",".","."],[".","9","8",".",".",".",".","6","."],["8",".",".",".","6",".",".",".","3"],["4",".",".","8",".","3",".",".","1"],["7",".",".",".","2",".",".",".","6"],[".","6",".",".",".",".","2","8","."],[".",".",".","4","1","9",".",".","5"],[".",".",".",".","8",".",".","7","9"]]
Output: [["5","3","4","6","7","8","9","1","2"],["6","7","2","1","9","5","3","4","8"],["1","9","8","3","4","2","5","6","7"],["8","5","9","7","6","1","4","2","3"],["4","2","6","8","5","3","7","9","1"],["7","1","3","9","2","4","8","5","6"],["9","6","1","5","3","7","2","8","4"],["2","8","7","4","1","9","6","3","5"],["3","4","5","2","8","6","1","7","9"]]
Explanation: The input board is shown above and the only valid solution is shown below:
![image](https://github.com/Google-Developer-Student-Club-CCOEW/Competitive-Programming-2023/assets/128240967/34cd452d-f850-4241-b52a-ddcdbc11d1be)

**Comment by gaurijoshi22** [comment]
Hey, I am Gauri Joshi (college-CCOEW). Can you please assign me this issue.

**Comment by Eesha04** [comment]
Name- Eesha Satvalekar
email - eesha.satvalekar@cumminscollege.in
I would like to work on this issue.
Please assign it to me.

**Comment by Pankaj4152** [comment]
Can you please assign this to me?
