### ISSUE TITLE
Find the Town Judge

### ISSUE THREAD

**Issue by saakshii12** [Google-Developer-Student-Club-CCOEW/Competitive-Programming-2023-GDSC-CUMMINS-X-GDSC-MMCOE#84]
**Write code in the preferred language and attach output with it.**

In a town, there are n people labeled from 1 to n. There is a rumor that one of these people is secretly the town judge.

If the town judge exists, then:

The town judge trusts nobody.
Everybody (except for the town judge) trusts the town judge.
There is exactly one person that satisfies properties 1 and 2.
You are given an array trust where trust[i] = [ai, bi] representing that the person labeled ai trusts the person labeled bi. If a trust relationship does not exist in trust array, then such a trust relationship does not exist.

**Return the label of the town judge if the town judge exists and can be identified, or return -1 otherwise.**

**Example 1:**

Input: n = 2, trust = [[1,2]]
Output: 2

**Example 2:**

Input: n = 3, trust = [[1,3],[2,3]]
Output: 3

**Example 3:**

Input: n = 3, trust = [[1,3],[2,3],[3,1]]
Output: -1

**Comment by iliketrains42** [comment]
Could you please assign this to me?

**Comment by GayatriJ-21** [comment]
Can you please Assign me this issue
Name-Gayatri Joshi
C number-UCE2021430
gayatri.joshi@cumminscollege.in
joshigayatri716@gmail.com (github)
TY Comp
Cummins college of engineering pune
