### ISSUE TITLE
Employee Importance

### ISSUE THREAD

**Issue by saakshii12** [Google-Developer-Student-Club-CCOEW/Competitive-Programming-2023-GDSC-CUMMINS-X-GDSC-MMCOE#85]
**Write code in the preferred language and attach output with it.**

You have a data structure of employee information, including the employee's unique ID, importance value, and direct subordinates' IDs.

You are given an array of employees employees where:

employees[i].id is the ID of the ith employee.
employees[i].importance is the importance value of the ith employee.
employees[i].subordinates is a list of the IDs of the direct subordinates of the ith employee.
Given an integer id that represents an employee's ID, return the total importance value of this employee and all their direct and indirect subordinates.

**Example 1:**
![image](https://github.com/Google-Developer-Student-Club-CCOEW/Competitive-Programming-2023/assets/128240967/1162b964-ca6a-43ba-a49c-39000ac97b05)
Input: employees = [[1,5,[2,3]],[2,3,[]],[3,3,[]]], id = 1
Output: 11
Explanation: Employee 1 has an importance value of 5 and has two direct subordinates: employee 2 and employee 3.
They both have an importance value of 3.
Thus, the total importance value of employee 1 is 5 + 3 + 3 = 11.

**Example 2:**
![image](https://github.com/Google-Developer-Student-Club-CCOEW/Competitive-Programming-2023/assets/128240967/c193768f-bf34-40a3-ac3f-edae1011b0c5)
Input: employees = [[1,2,[5]],[5,-3,[]]], id = 5
Output: -3
Explanation: Employee 5 has an importance value of -3 and has no direct subordinates.
Thus, the total importance value of employee 5 is -3.

**Comment by aditya-shrimali** [comment]
Hi @saakshii12 , i wan't to solve this issue . Can you please tell me how can I do that
