### ISSUE TITLE
Subarray Sum Equals K

### ISSUE THREAD

**Issue by saakshii12** [Google-Developer-Student-Club-CCOEW/Competitive-Programming-2023-GDSC-CUMMINS-X-GDSC-MMCOE#9]
**Write code in the preferred language and attach output with it.**

**Given an array of integers nums and an integer k, return the total number of subarrays whose sum equals to k.**

A subarray is a contiguous non-empty sequence of elements within an array.

**Example 1:**

Input: nums = [1,1,1], k = 2
Output: 2

**Example 2:**

Input: nums = [1,2,3], k = 3
Output: 2

**Comment by akanksha1131** [comment]
Can you please assign this to me?
Akanksha Kale IT, Cummins College

**Comment by saakshii12** [comment]
Sakshi Umredkar 
UIN2022764
CCOEW SY
