### ISSUE TITLE
Reconstruct Itinerary

### ISSUE THREAD

**Issue by saakshii12** [Google-Developer-Student-Club-CCOEW/Competitive-Programming-2023-GDSC-CUMMINS-X-GDSC-MMCOE#93]
**Write code in the preferred language and attach output with it.**

**You are given a list of airline tickets where tickets[i] = [fromi, toi] represent the departure and the arrival airports of one flight. Reconstruct the itinerary in order and return it.**

All of the tickets belong to a man who departs from "JFK", thus, the itinerary must begin with "JFK". If there are multiple valid itineraries, you should return the itinerary that has the smallest lexical order when read as a single string.

For example, the itinerary ["JFK", "LGA"] has a smaller lexical order than ["JFK", "LGB"].
You may assume all tickets form at least one valid itinerary. You must use all the tickets once and only once.

**Example 1:**
![image](https://github.com/Google-Developer-Student-Club-CCOEW/Competitive-Programming-2023/assets/128240967/59ce2466-1c92-4b9c-92d9-08a53dfb174a)
Input: tickets = [["MUC","LHR"],["JFK","MUC"],["SFO","SJC"],["LHR","SFO"]]
Output: ["JFK","MUC","LHR","SFO","SJC"]

**Example 2:**
![image](https://github.com/Google-Developer-Student-Club-CCOEW/Competitive-Programming-2023/assets/128240967/bbf5ba0e-5684-4418-822d-233120df90d1)
Input: tickets = [["JFK","SFO"],["JFK","ATL"],["SFO","ATL"],["ATL","JFK"],["ATL","SFO"]]
Output: ["JFK","ATL","JFK","SFO","ATL","SFO"]
Explanation: Another possible reconstruction is ["JFK","SFO","ATL","JFK","ATL","SFO"] but it is larger in lexical order.

**Comment by Eesha04** [comment]
Name- Eesha Satvalekar
email - eesha.satvalekar@cumminscollege.in 
Can you please assign this issue to me?
