### ISSUE TITLE
Path Sum III

### ISSUE THREAD

**Issue by Sonia312** [Google-Developer-Student-Club-CCOEW/Competitive-Programming-2023-GDSC-CUMMINS-X-GDSC-MMCOE#96]
**Write code in the preferred language and attach output with it.**

Given the root of a binary tree and an integer targetSum, return the number of paths where the sum of the values along the path equals targetSum.

The path does not need to start or end at the root or a leaf, but it must go downwards (i.e., traveling only from parent nodes to child nodes).

 

**Example 1:**

<img width="337" alt="image" src="https://github.com/Google-Developer-Student-Club-CCOEW/Competitive-Programming-2023/assets/101570119/150dd96c-ef45-40c5-aeab-4200869bc92e">

Input: root = [10,5,-3,3,2,null,11,3,-2,null,1], targetSum = 8
Output: 3
Explanation: The paths that sum to 8 are shown.

**Example 2:**

Input: root = [5,4,8,11,null,13,4,7,2,null,null,5,1], targetSum = 22
Output: 3

**Comment by sejalphatangare** [comment]
Hi! pls assign me this issue
Sejal Phatangare
UCE2021457
Cummins College Of Engineering
