### ISSUE TITLE
Binary Tree Cameras

### ISSUE THREAD

**Issue by Sonia312** [Google-Developer-Student-Club-CCOEW/Competitive-Programming-2023-GDSC-CUMMINS-X-GDSC-MMCOE#99]
**Write code in the preferred language and attach output with it.**

You are given the root of a binary tree. We install cameras on the tree nodes where each camera at a node can monitor its parent, itself, and its immediate children.

Return the minimum number of cameras needed to monitor all nodes of the tree.

 

**Example 1:**

<img width="104" alt="image" src="https://github.com/Google-Developer-Student-Club-CCOEW/Competitive-Programming-2023/assets/101570119/9c665513-c2a6-482d-bb36-e44e70f7b2ba">

Input: root = [0,0,null,0,0]
Output: 1
Explanation: One camera is enough to monitor all nodes if placed as shown.

**Example 2:**

<img width="104" alt="image" src="https://github.com/Google-Developer-Student-Club-CCOEW/Competitive-Programming-2023/assets/101570119/4d04755f-6e55-4e80-8743-7a21785f9d74">

Input: root = [0,0,null,0,null,0,null,null,0]
Output: 2
Explanation: At least two cameras are needed to monitor all nodes of the tree. The above image shows one of the valid configurations of camera placement.

**Comment by sejalphatangare** [comment]
Hi1 pls assign this issue to me
Sejal Phatangare
UCE2021457
Cummins college of engineering,Pune
